//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebEncodageEmploi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    public partial class Emploi
    {
        public decimal ID { get; set; }
        
        public bool EstSoumis { get; set; }

        [Required(ErrorMessage = "Ce champ est obligatoire")]
        public System.DateTime DateDebut { get; set; }
        
        public decimal IDTravailleur { get; set; }
        
        public decimal CodeProfession { get; set; }

        [DateGreaterThanAttribute("DateDebut")]
        public Nullable<System.DateTime> DateFin { get; set; }
        
        public decimal NumeroEntreprise { get; set; }
    
        public virtual Entreprise Entreprise { get; set; }
        public virtual Profession Profession { get; set; }
        public virtual Travailleur Travailleur { get; set; }


        public string displayEstSoumis
        {
            get { return (EstSoumis) ? "Oui" : "Non"; }
        }

        public string displayDateDebut
        {
            get
            {
                if(DateDebut == null)
                {
                    return "";
                }
                else
                {
                    return DateDebut.ToString("dd/MM/yyyy");
                }
            }
        }

        public string displayDateFin
        {
            get
            {
                if (DateFin == null)
                {
                    return "";
                }
                else
                {
                    return ((DateTime)DateFin).ToString("dd/MM/yyyy");
                }
            }
        }


        private class DateGreaterThanAttribute : ValidationAttribute
        {
            private string DateDebut { get; set; }

            public DateGreaterThanAttribute(string dateDebut)
            {
                DateDebut = dateDebut;
            }

            protected override ValidationResult IsValid(object value, ValidationContext validationContext)
            {
                Nullable<System.DateTime> endDate = (Nullable<System.DateTime>)value;

                DateTime beginningDate = (DateTime)validationContext.ObjectType.GetProperty(DateDebut).GetValue(validationContext.ObjectInstance, null);

                if (endDate == null)
                {
                    return ValidationResult.Success;
                }
                else
                {
                    if (endDate >= beginningDate)
                    {
                        return ValidationResult.Success;
                    }
                    else
                    {
                        return new ValidationResult("La date de fin doit être plus grande ou égale à la date de début");
                    }
                }
            }
        }


    }
}
