//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AppWebEncodageEmploi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Localite
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Localite()
        {
            this.Entreprises = new HashSet<Entreprise>();
            this.Travailleurs = new HashSet<Travailleur>();
        }
    
        public decimal ID { get; set; }
        public string Nom { get; set; }
        public string CodePostal { get; set; }
        public string Pays { get; set; }

        public string CodeNom
        {
            get { return CodePostal + ", " + Nom; }
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Entreprise> Entreprises { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Travailleur> Travailleurs { get; set; }
    }
}
